name: ArangoDB Backup Job Publisher
on:
  push:
    branches: [main]
env:
  arango_username: ${{ secrets.ARANGO_USERNAME }}
  arango_host: ${{ secrets.ARANGO_HOST }}
  arango_port: ${{ secrets.ARANGO_PORT }}
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: modified-files
        uses: jitterbit/get-changed-files@v1
      - name: Build & Push Containers to DockerHub
        run: |
          cd scripts/backup-arangodb
          for changed_file in ${{ steps.modified-files.outputs.all }}; do
            if [[ $changed_file == scripts/backup-arangodb/* ]] ;
            then
              docker build \
                --build-arg arango_host=$arango_host \
                --build-arg arango_port=$arango_port \
                --build-arg arango_username=$arango_username \
                -t "toshiqcri/backup-arangodb:latest" \
                --no-cache .

              docker push "toshiqcri/backup-arangodb:latest"
              break
            fi
          done
