name: Ethereum Blockchain Parser Job Publisher
on:
  push:
    branches: [main]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: modified-files
        uses: jitterbit/get-changed-files@v1
      - name: Build & Push Containers to DockerHub
        run: |
          cd scripts/eth-parser
          for changed_file in ${{ steps.modified-files.outputs.all }}; do
            if [[ $changed_file == scripts/eth-parser/* ]] ;
            then
              docker build -t "toshiqcri/eth-etl-parser:latest" --no-cache .
              docker push "toshiqcri/eth-etl-parser:latest"
              break
            fi
          done
