name: Publish
on:
  push:
    branches: [ main ]
env:
  es_host: ${{ secrets.ES_CONNECTION_HOST }}
  es_port: ${{ secrets.ES_CONNECTION_PORT }}
  redis_host: ${{ secrets.CRAWLERS_REDIS_CONNECTION_HOST }}
  redis_port: ${{ secrets.CRAWLERS_REDIS_CONNECTION_PORT }}
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: modified-files
        uses: jitterbit/get-changed-files@v1
      - name: Build & Push Containers to DockerHub
        run: |
          for changed_file in ${{ steps.modified-files.outputs.all }}; do
            if [[ $changed_file == scripts* ]] ;
            then
              file=${changed_file##*/}

              docker build \
                --build-arg "modified_file=$changed_file" \
                --build-arg elasticsearch_host=$es_host \
                --build-arg elasticsearch_port=$es_port \
                --build-arg redis_host=$redis_host \
                --build-arg redis_port=$redis_port \
                -t "toshiqcri/${file%%_*}:latest" \
                --no-cache .

              docker push "toshiqcri/${file%%_*}:latest"
            fi
          done
