name: Publish
on:
  push:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: modified-files
        uses: jitterbit/get-changed-files@v1
      - name: Build & Push Containers to DockerHub
        run: |
          for changed_file in ${{ steps.modified-files.outputs.all }}; do
            if [[ $changed_file == scripts* ]] ;
            then
              file_segments=(${IN//\// })
              echo ${file_segments[0]}
              echo ${file_segments[1]}
              docker build --build-arg modified_file=$changed_file -t "${file_segments[1]}:latest"
            fi
          done
          docker images
